FROM golang:1.12-alpine AS build

ENV GOPATH=/go

WORKDIR /go/src/github.com/ffilippopoulos/k8s-envoy-control-plane
COPY . /go/src/github.com/ffilippopoulos/k8s-envoy-control-plane

# https://github.com/golang/go/issues/27639
RUN apk add build-base

RUN apk --no-cache add ca-certificates git && \
  go get -u github.com/golang/dep/cmd/dep && \
  /go/bin/dep ensure
