# https://github.com/golang/dep

#[[constraint]]
#  name = "k8s.io/api"
#  version="kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version="kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/client-go"
  version="v11.0.0"

[[constraint]]
  name = "github.com/envoyproxy/go-control-plane"
  version = "0.8.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.4.2"
