# https://github.com/golang/dep

#[[constraint]]
#  name = "k8s.io/api"
#  version="kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version="kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/client-go"
  version="v11.0.0"

[[constraint]]
  name = "k8s.io/sample-controller"
  version="kubernetes-1.14.2"


#[[constraint]]
#  name = "github.com/envoyproxy/go-control-plane"
#  version = "0.8.0"
