apiVersion: egresslistener.envoy.uw.systems/v1alpha1
kind: EgressListener
metadata:
  name: example-egress-listener
spec:
  nodename: test-app
  listenport: 9090
  targetport: 8080
  targetcluster: test-cluster
  lbpolicy: "tcp"
